from tkinter import *
beat=Tk()
beat.geometry("1660x800+0+0")
beat.config(bg="white")
beat.title("NAMAN JAIN FORM ")
l=Label(text="MY INFORMATION",fg="cyan",bg="white",font=("algerian",18,"bold"),width=16)
l.pack()
l1=Label(text="NAME",fg="tomato",bg="oldlace",font=("gabriola",14,"italic"),width=12)
l1.place(x=80,y=120)
e1=Entry(width=15,bd=7,font=("rockwell extra bold",12,"bold"),bg="floralwhite",fg="dodgerblue")
e1.place(x=560,y=120)
l2=Label(text="FATHERS NAME",bg="oldlace",fg="tomato",font=("gabriola",14,"italic"),width=14)
l2.place(x=80,y=200)
e2=Entry(width="15",bd=7,font=("rockwell extra bold",12,"bold"),bg="floralwhite",fg="dodgerblue")
e2.place(x=560,y=200)
l3=Label(text="EMAIL ID",bg="oldlace",fg="tomato",font=("gabriola",14,"italic"),width=15)
l3.place(x=80,y=280)
e3=Entry(width="15",bd=7,font=("rockwell extra bold",12,"bold"),bg="floralwhite",fg="dodgerblue")
e3.place(x=560,y=280)
l4=Label(text="CONTACT NUMBER",bg="oldlace",fg="tomato",font=("gabriola",14,"italic"),width=16)
l4.place(x=80,y=360)
e4=Entry(width="15",bd=7,font=("rockwell extra bold",12,"bold"),bg="floralwhite",fg="dodgerblue")
e4.place(x=560,y=360)
l5=Label(text="FULL ADDRESS",bg="oldlace",fg="tomato",font=("gabriola",14,"italic"),width=20)
l5.place(x=80,y=440)
e5=Entry(width="34",bd=7,font=("rockwell extra bold",12,"bold"),bg="floralwhite",fg="dodgerblue")
e5.place(x=560,y=440)
l6=Label(text="YOUR MESSAGE",bg="oldlace",fg="tomato",font=("gabriola",14,"italic"),width=20)
l6.place(x=80,y=520)
e6=Entry(width="34",bd=7,font=("rockwell extra bold",12,"bold"),bg="floralwhite",fg="dodgerblue")
e6.place(x=560,y=520)
b1=Button(text="submit",fg="black",bg="lightcoral",font=(13),width=15)
b1.place(x=40,y=680)
b3=Button(text="next",fg="black",bg="lightcoral",font=(13),width=15)
b3.place(x=1040,y=680)
def reset():
    e1.delete(0,END)
    e2.delete(0,END)
    e3.delete(0,END)
    e4.delete(0,END)
    e5.delete(0,END)
    e6.delete(0,END)
b2=Button(text="reset",fg="black",bg="lightcoral",font=(13),width=15,command=reset)
b2.place(x=540,y=680)
beat.mainloop()